import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import localFont from 'next/font/local';

const myFont = localFont({
    src: '../../public/fonts/helveticaneueltarabicroman1.ttf',
});

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

// الصفحات اللي مش عايز فيها Navbar و Footer

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
    params: { pathname: string }; // استقبل الـ pathname من كل صفحة
}) {
    return (
        <html lang="ar" dir="rtl">
            <body className={myFont.className}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
