import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import localFont from 'next/font/local';

const myFont = localFont({
    src: '../../public/fonts/helveticaneueltarabicroman1.ttf',
});


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};


export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ar" dir="rtl">
            <body className={myFont.className}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
